vich_uploader:
    db_driver: orm

    mappings:
        profil_photo:
            uri_prefix: /uploads/profils
            upload_destination: '%kernel.project_dir%/public/uploads/profils'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        challenge_photo:
            uri_prefix: /uploads/challenge
            upload_destination: '%kernel.project_dir%/public/uploads/challenge'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        clan_logo:
            uri_prefix: /uploads/clan/logo
            upload_destination: '%kernel.project_dir%/public/uploads/clan/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        clan_banner:
            uri_prefix: /uploads/clan/banner
            upload_destination: '%kernel.project_dir%/public/uploads/clan/banner'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        gpx_track:
            uri_prefix: /uploads/challenge/gpx
            upload_destination: '%kernel.project_dir%/public/uploads/challenge/gpx'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
