vich_uploader:
    db_driver: orm

    mappings:
        profil_photo:
            uri_prefix: /uploads/profils
            upload_destination: '%kernel.project_dir%/public/uploads/profils'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        challenge_photo:
            uri_prefix: /uploads/challenge
            upload_destination: '%kernel.project_dir%/public/uploads/challenge'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
